[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4",
    "google-genai",
    "jinja2",
    "requests",
    "streamlit",
    "trafilatura",
]
